const DetailsSection = () => {
  return (
    <div className="bg-white p-6 rounded-lg shadow-md border border-gray-200 space-y-6 text-gray-600">
      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          What is Section 8 Company? - Companies Act, 2013
        </h2>
        <p>
          According to the Companies Act 2013, a Section 8 company means an
          organization whose objectives are to promote arts, commerce, science,
          research, education, sports, charity, social welfare, religion,
          environmental protection, or other similar activities goals. These
          entities utilize their profits to achieve their mission and do not
          distribute dividends to their shareholders.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Overview of Section 8 Company Registration
        </h2>
        <p className="mb-2">
          A Section 8 Company is a type of corporation established to promote
          non-profit activities, such as education, social welfare, environment
          preservation, arts, sports, charity, and more. This follows the
          provisions of the Companies Act 2013.
        </p>
        <p>
          The essential purpose of registering a Section 8 Company is to
          encourage non-profitable goals, including but not limited to trade,
          arts, commerce, education, charity, environmental protection, sports
          research, and social welfare. To register a Section 8 Company, a
          minimum of two directors are required, and there is no requirement for
          a minimum paid-up capital to set up such a company.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Key Points about Section 8 Company Act
        </h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            In India, Non-Governmental Organizations (NGOs) can be registered
            under the Registrar of Societies or as a non-profit entity under
            Section 8 Company of the Companies Act, 2013.
          </li>
          <li>
            Profit generated by Section 8 Companies cannot be used for purposes
            other than charitable objectives and cannot be distributed among
            shareholders.
          </li>
          <li>
            Section 8 Companies are similar to the erstwhile Section 25 Company
            under the Company Act 1956. As per the prevailing Company Act, these
            are now recognized as Section 8 Companies.
          </li>
          <li>
            Section 8 Companies are required to comply with the provisions of
            the Companies Act 2013. They are mandated to maintain books of
            accounts, file returns with the Registrar of Companies (ROCs), and
            comply with GST and IT Act.
          </li>
          <li>
            Any changes to the charter documents like the Articles of
            Association (AoA) and Memorandum of Association (MoA) require the
            government's consent.
          </li>
        </ul>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Benefits of Opening a Section 8 Company in India
        </h2>
        <p className="mb-4">
          Incorporating a Section 8 company in India offers numerous advantages,
          some highlighted below.
        </p>
        <div className="space-y-4">
          <div>
            <h3 className="font-semibold text-gray-700">Tax Exemption</h3>
            <p>
              Section 8 companies registered under section 12AA of the Income
              Tax Act are eligible for a 100% tax exemption, as they utilize
              their profits for charitable purposes. This is a significant
              benefit as the profits generated by such entities are non-taxable.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">
              No Minimum Capital Requirement
            </h3>
            <p>
              Unlike public limited companies, Section 8 entities do not have a
              minimum capital requirement. They can adjust their capital
              structure according to their growth, giving them more flexibility.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">
              Separate Legal Entity
            </h3>
            <p>
              Section 8 companies have a separate legal identity and perpetual
              existence, just like other registered companies. This increases
              their credibility and provides them with more autonomy and legal
              standing.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">
              Increased Credibility
            </h3>
            <p>
              Section 8 companies are subject to strict legal compliance
              frameworks, enhancing their credibility regarding legal standing.
              Unlike NGOs and trusts, Section 8 entities follow stringent
              compliances post-registration, making them more trustworthy.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">No Title Required</h3>
            <p>
              Section 8 companies are free to choose a name that suits their
              liking during the registration process. Unlike other registered
              structures, they are not required to affix the term "Section 8"
              after their name.
            </p>
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Who can Form a Section 8 Company?
        </h2>
        <p className="mb-2">
          Here are the criteria that specify who can form a Section 8 company.
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>
            An Indian national or Hindu Undivided Family (HUF) can incorporate a
            Section 8 Company.
          </li>
          <li>The entity must have at least one director.</li>
          <li>
            The primary object of the Section 8 Company Act should be related to
            promoting art and science, sports, charitable activities, education,
            or providing financial assistance to individuals from lower-income
            groups.
          </li>
        </ul>
        <p className="mt-2">
          These eligibility criteria ensure that the Section 8 Company operates
          to promote social welfare and contribute to the greater good of
          society.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Mandatory legal requirements for the Incorporation of Section 8
          Company
        </h2>
        <p className="mb-4">
          Before applying for the process of incorporation of Section 8 company
          in India, specific legal requisites must be fulfilled. These
          requirements are as follows:
        </p>
        <div className="space-y-4">
          <div>
            <h3 className="font-semibold text-gray-700">Number of Directors</h3>
            <p>
              A minimum of two directors is required if the Section 8 entity
              intends to operate as a private limited company. However, a
              minimum of three directors are required if the entity aims to
              operate as a public limited company.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">Number of Members</h3>
            <p>
              If the Section 8 Company Act aims to function as a private limited
              company, the number of members is capped at 200 by the Ministry of
              Corporate Affairs (MCA). However, there is no such limit for
              Section 8 entities with a business structure like a public limited
              company.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">
              Capital Requirement and Name
            </h3>
            <p>
              According to the Companies Act 2013, Section 8 entities are not
              required to maintain a minimum paid-up capital. Moreover, NGOs
              operating as Section 8 entities are not obligated to affix terms
              like private limited or limited in their name.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-gray-700">Company Objects</h3>
            <p>
              Only entities with non-profit objectives are eligible for Section
              8 registration. The Memorandum of Association and Articles of
              Association must clearly state such goals for which the Company is
              established. Any profits the Section 8 entity generates must be
              utilized for charitable purposes or reinvested in the entity. The
              profit of Section 8 entities is not available to its members in
              any form. These legal requisites ensure that Section 8 companies
              operate with transparency and the intended purpose of promoting
              social welfare.
            </p>
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Section 8 Company Incorporation Process
        </h2>
        <p className="mb-4">
          The process of incorporating Section 8 companies in India involves the
          following steps:
        </p>
        <ol className="list-decimal list-inside space-y-4">
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              Obtain Digital Signature Certificate (DSC)
            </h4>
            <p className="mt-1">
              The first step is to obtain a Digital Signature Certificate (DSC)
              for the proposed directors of the Section 8 Company. This
              certificate is required for the online filing of documents with
              the Ministry of Corporate Affairs (MCA).
            </p>
          </li>
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              Obtain Director Identification Number (DIN)
            </h4>
            <p className="mt-1">
              After obtaining the DSC, the next step is to apply for a Director
              Identification Number (DIN) for the proposed directors.
            </p>
          </li>
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              Reserve the Company Name
            </h4>
            <p className="mt-1">
              The next step is to reserve the name of the proposed Company with
              the MCA. The Section 8 company name should be unique and not be
              similar to any existing company name.
            </p>
          </li>
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              File the Application for Incorporation
            </h4>
            <p className="mt-1">
              After the company name is approved, the next step is to apply for
              Section 8 Company incorporation.
            </p>
          </li>
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              Obtain a License for Section 8 Company
            </h4>
            <p className="mt-1">
              Once the application for incorporation is approved, the next step
              is to obtain a license for the Section 8 Company.
            </p>
          </li>
          <li>
            <h4 className="font-semibold text-gray-700 inline">
              Obtain a Certificate of Incorporation
            </h4>
            <p className="mt-1">
              After obtaining the license, the MCA issues a Certificate of
              Incorporation. This certificate confirms the incorporation of the
              Section 8 Company.
            </p>
          </li>
        </ol>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Donations/Funding of Section 8 Company
        </h2>
        <p>
          A Section 8 Company cannot collect capital through deposits but can
          accept donations from the public. Several methods are available to
          raise funds, such as foreign donations, equity funding, and domestic
          donations.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Registration under Section 12AA and 80G for Section 8 Companies
        </h2>
        <p>
          Registering a Section 8 company under Section 12AA and obtaining
          approval under Section 80G offers significant benefits. Section 12AA
          registration exempts the company's income from taxation if used for
          charitable purposes. Section 80G registration allows donors to claim
          tax deductions on their contributions.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">
          Streamline Section 8 Company Registration with CA PI
        </h2>
        <p>
          CA PI is a trusted partner for entrepreneurs and organizations looking
          to obtain Section 8 company registration in India. With our expertise
          and seamless online platform, CA PI simplifies the complex process of
          registering a Section 8 company, ensuring that all legal formalities
          are met.
        </p>
      </div>
    </div>
  );
};

export default DetailsSection;
