// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flpejsholttqsphleids.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscGVqc2hvbHR0cXNwaGxlaWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTg0MTcsImV4cCI6MjA2NTUzNDQxN30.fEW-uTqoaVl342A_Vr09NyhqOuQEQzezhS53xhnZLyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);